In [16]:
import pandas as pd 
data = pd.read_csv("./featuresdf.csv")
data

,id,name,artists,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,7qiZfU4dY1lWllzX7mPBI,Shape of You,Ed Sheeran,0.825,0.652,1.0,-3.183,0.0,0.0802,0.5810,0.000000,0.0931,0.9310,95.977,233713.0,4.0
1,5CtI0qwDJkDQGwXD1H1cL,Despacito - Remix,Luis Fonsi,0.694,0.815,2.0,-4.328,1.0,0.1200,0.2290,0.000000,0.0924,0.8130,88.931,228827.0,4.0
2,4aWmUDTfIPGksMNLV2rQP,Despacito (Featuring Daddy Yankee),Luis Fonsi,0.660,0.786,2.0,-4.757,1.0,0.1700,0.2090,0.000000,0.1120,0.8460,177.833,228200.0,4.0
3,6RUKPb4LETWmmr3iAEQkt,Something Just Like This,The Chainsmokers,0.617,0.635,11.0,-6.769,0.0,0.0317,0.0498,0.000014,0.1640,0.4460,103.019,247160.0,4.0
4,3DXncPQOG4VBw3QHh3S81,I'm the One,DJ Khaled,0.609,0.668,7.0,-4.284,1.0,0.0367,0.0552,0.000000,0.1670,0.8110,80.924,288600.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1PSBzsahR2AKwLJgx8ehB,Bad Things (with Camila Cabello),Machine Gun Kelly,0.675,0.690,2.0,-4.761,1.0,0.1320,0.2100,0.000000,0.2870,0.2720,137.817,239293.0,4.0
96,0QsvXIfqM0zZoerQfsI9l,Don't Let Me Down,The Chainsmokers,0.542,0.859,11.0,-5.651,1.0,0.1970,0.1600,0.004660,0.1370,0.4030,159.797,208053.0,4.0
97,7mldq42yDuxiUNn08nvzH,Body Like A Back Road,Sam Hunt,0.731,0.469,5.0,-7.226,1.0,0.0326,0.4630,0.000001,0.1030,0.6310,98.963,165387.0,4.0
98,7i2DJ88J7jQ8K7zqFX2fW,Now Or Never,Halsey,0.658,0.588,6.0,-4.902,0.0,0.0367,0.1050,0.000001,0.1250,0.4340,110.075,214802.0,4.0
99,1j4kHkkpqZRBwE0A4CN4Y,Dusk Till Dawn - Radio Edit,ZAYN,0.258,0.437,11.0,-6.593,0.0,0.0390,0.1010,0.000001,0.1060,0.0967,180.043,239000.0,4.0

In [17]:
data.drop([
    "id",
    "danceability",
    "energy",
    "key",
    "loudness",
    "mode",
    "speechiness",
    "acousticness",
    "instrumentalness",
    "liveness",
    "valence",
    "tempo",
    "name",
    "artists"
],
axis=1,
inplace=True
)
data

    duration_ms  time_signature
0      233713.0             4.0
1      228827.0             4.0
2      228200.0             4.0
3      247160.0             4.0
4      288600.0             4.0
..          ...             ...
95     239293.0             4.0
96     208053.0             4.0
97     165387.0             4.0
98     214802.0             4.0
99     239000.0             4.0

[100 rows x 2 columns]

In [12]:
data.columns

Index(['name', 'artists', 'duration_ms', 'time_signature'], dtype='object')

In [18]:
x_cols = [x for x in data.columns if x != "duration_ms"]


# Split the data into two dataframes
X_data = data[x_cols]
y_data = data['duration_ms']

# # alternatively:
# X_data = data.copy()
# y_data = X_data.pop('churned')
data

    duration_ms  time_signature
0      233713.0             4.0
1      228827.0             4.0
2      228200.0             4.0
3      247160.0             4.0
4      288600.0             4.0
..          ...             ...
95     239293.0             4.0
96     208053.0             4.0
97     165387.0             4.0
98     214802.0             4.0
99     239000.0             4.0

[100 rows x 2 columns]

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

knn = knn.fit(X_data, y_data)

y_pred = knn.predict(X_data)

In [21]:
def accuracy(real, predict):
    return sum(y_data == y_pred) / float(real.shape[0])

In [22]:
print(accuracy(y_data, y_pred))

0.01

In [23]:
knn = KNeighborsClassifier(n_neighbors=5, weights='distance')

knn = knn.fit(X_data, y_data)

y_pred = knn.predict(X_data)

print(accuracy(y_data, y_pred))

0.02